-- Seed the original app exercise library into Supabase and add protocol tagging.
-- Makes the exercises table the single source of truth for the Exercise Library.

ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS protocol_slugs text[];

-- Re-seed safety: replace prior versions of these exercises by name
DELETE FROM public.exercises WHERE name IN (
  'Push-ups',
  'Squats',
  'Forearm Plank',
  'Lunges',
  'Calf Raises',
  'Calf & Hamstring Stretch on Heel Wedges',
  'Ankle Inversion',
  'Ankle Eversion',
  'Toe Extension Plank',
  'Wrist Flexion/Extension with Forearm Spinner',
  'Reverse Fly',
  'Standing Hip Abduction',
  'Side Plank',
  'Overhead Shoulder Flexion on Foam Roller (PVC Pipe)',
  'Supine Core Stability with Band Hold'
);

INSERT INTO public.exercises (name, description, difficulty, intensity, duration, equipment, muscle_groups, joint_movements, categories, instructions, baseline, progression, regression, video_url)
VALUES
(
  'Push-ups',
  'Fundamental upper body strengthening exercise',
  'intermediate', 'moderate', '4-10 reps',
  ARRAY['None', 'Foam Roller']::text[],
  ARRAY['Pectoralis Major', 'Anterior Deltoids', 'Triceps Brachii', 'Transverse Abdominis', 'Pectoralis Minor', 'Rhomboid', 'Teres Major']::text[],
  ARRAY['Shoulder Flexion', 'Elbow Extension', 'Wrist Extension', 'Shoulder Retraction']::text[],
  ARRAY['strength']::text[],
  'Start in a plank position with your hands right under your chest or shoulders. Wrist and elbow position can change this exercise drastically. Elbows should not exceed 45 degrees away from ribs. Elbows being closer to ribs will increase difficulty of exercise on wrists and shoulders. After finding correct position lower body as one unit from head to toes towards the floor. Taking at least 5 seconds to get to the bottom pull shoulder blades back and together, while keeping core active and hips at the same height as the shoulders from the ground.',
  'Standard push-up from toes',
  'Decline push-ups with feet elevated on chair',
  'Incline push-ups with hands on chair',
  'https://www.youtube.com/embed/IODxDxX7oi4'
),
(
  'Squats',
  'The ultimate sit crushing exercise. Full body engagement.',
  'advanced', 'high', '3-15 Reps',
  ARRAY['2.5 lbs plates', '5'' PVC Pipe']::text[],
  ARRAY['Quadriceps', 'Gluteus Maximus', 'Hamstrings', 'Erector Spinae']::text[],
  ARRAY['Ankle Dorsiflexion', 'Shoulder retraction', 'core stability', 'Knee flexion', 'knee extension', 'hip flexion', 'hip extension']::text[],
  ARRAY['mobility', 'strength']::text[],
  'Put the 2.5 lbs plates under your heels about shoulder width apart. Grab a light weight (At least 5-10 pounds) and hold it out in front of your face or eyes. You can add a chair behind you to assist where to aim. While keeping upright posture, very slowly start lowering yourself towards the seat loading our weight backward into our hips and glutes. Touch the seat and gentle return back to start by pushing through your glutes.',
  'Bodyweight squat to 90 degrees',
  'Squat with weight plates or single-leg pistol squat',
  'Squat to chair or with heel wedges for ankle mobility assistance',
  NULL
),
(
  'Forearm Plank',
  'A foundational core stability exercise that trains the body to resist extension and maintain full-body tension. Builds strength in the deep core, shoulders, and glutes for posture and performance.',
  'beginner', 'moderate', '2–3 sets of 20–60 seconds (progress to 90 seconds)',
  ARRAY['None']::text[],
  ARRAY['Rectus Abdominis', 'Transverse Abdominis', 'External Obliques', 'Internal Obliques', 'Gluteus Maximus', 'Anterior Deltoids', 'Serratus Anterior', 'Erector Spinae', 'Quadriceps']::text[],
  ARRAY['Shoulder Flexion', 'Lumbar Neutral', 'Hip Neutral']::text[],
  ARRAY['strength']::text[],
  'Start on the floor with elbows directly under shoulders and forearms flat. Extend legs straight back, toes on the ground. Brace your core, squeeze glutes, and keep ribs down. Maintain a straight line from head to heels — don''t let hips sag or pike. Hold position for time, breathing steadily.',
  'Forearm plank with elbows under shoulders',
  'Single-arm plank or plank with leg lifts',
  'Incline plank with hands on chair/box or knee plank',
  'https://www.youtube.com/embed/Z9cO9_TsAV8'
),
(
  'Lunges',
  'Unilateral lower body exercise for strength, balance, and coordination',
  'beginner', 'moderate', '45 seconds each leg',
  ARRAY['None']::text[],
  ARRAY['Quadriceps', 'Gluteus Maximus', 'Hamstrings', 'Gastrocnemius', 'Soleus']::text[],
  ARRAY['Ankle Dorsiflexion', 'Knee Flexion', 'Hip Flexion', 'Lumbar Neutral', 'Cervical Neutral']::text[],
  ARRAY['mobility', 'strength']::text[],
  'Step forward with one leg, lowering hips until both knees are bent at 90 degrees. Keep front knee tracking over ankle, back knee pointing down, and torso upright. Push through front heel to return.',
  'Forward lunge with bodyweight',
  'Walking lunges or lunges with weight plates',
  'Stationary lunge with chair support or reverse lunge',
  'https://www.youtube.com/embed/QE1GDSVObyE'
),
(
  'Calf Raises',
  'Lower leg exercise for calf strength and ankle stability',
  'beginner', 'low', '45 seconds',
  ARRAY['None']::text[],
  ARRAY['Calves', 'Ankles']::text[],
  ARRAY['Ankle Plantarflexion']::text[],
  ARRAY['strength']::text[],
  'Stand with feet hip-width apart. Rise up onto toes by pushing through balls of feet. Hold briefly at top then lower slowly with control.',
  'Double-leg calf raises on flat ground',
  'Single-leg calf raises or calf raises on heel wedges',
  'Calf raises with chair support',
  'https://www.youtube.com/embed/QE1GDSVObyE'
),
(
  'Calf & Hamstring Stretch on Heel Wedges',
  'A mobility drill that combines deep ankle dorsiflexion with a hip hinge to lengthen the hamstrings while improving calf mobility. Builds control and flexibility for squats, deadlifts, and overall lower-body function.',
  'beginner', 'high', 'Dynamic: 8-12 slow, controlled reps | Long-Hold: 2-3 sets of 30-90 seconds',
  ARRAY['Heel Wedges', 'Yoga Blocks (optional)', '5'' PVC Pipe or light weight (optional)']::text[],
  ARRAY['Hamstrings (biceps femoris, semitendinosus, semimembranosus)', 'Gastrocnemius & Soleus (calves)', 'Core (rectus abdominis, obliques, erectors)', 'Glutes (isometric)', 'Small foot stabilizers']::text[],
  ARRAY['Ankle Dorsiflexion', 'Knee Extension', 'Hip Flexion', 'Lumbar Neutral']::text[],
  ARRAY['mobility']::text[],
  'Place your heels on the heel wedges to put ankles into deep dorsiflexion. Stand tall with feet about hip-width apart, spine long and flat. Begin a hip hinge by pushing hips and butt backward as far as possible, stopping right before you lose balance — this is your true end range. Keep knees extended and chest lifted as hamstrings lengthen. Use yoga blocks under your hands for support at end range if needed. To progress: Hold a light weight (e.g., 5'' PVC Pipe or small dumbbell) in front of you, letting it gently pull you deeper into the stretch while maintaining knee extension and a neutral spine. Return to standing tall under control.',
  'Calf & hamstring stretch on heel wedges with yoga block support',
  'Add light weight (5'' PVC Pipe or dumbbell) for deeper stretch',
  'Hip hinge stretch without heel wedges or with chair support',
  'https://www.youtube.com/embed/9g6_GyvFqFo'
),
(
  'Ankle Inversion',
  'Strengthening exercise for the medial ankle muscles using resistance band',
  'beginner', 'low', '10-25 reps',
  ARRAY['Yellow Perform Better Band']::text[],
  ARRAY['Tibialis Posterior', 'Flexor Digitorum Longus', 'Flexor Hallucis Longus']::text[],
  ARRAY['Ankle Inversion']::text[],
  ARRAY['strength']::text[],
  'Sit with legs extended. Loop the yellow band around your foot and hold the other end. Turn your foot inward against the resistance, moving slowly and controlled. Return to neutral position.',
  'Ankle inversion with yellow band resistance',
  'Ankle inversion with stronger resistance band',
  'Ankle inversion without resistance',
  NULL
),
(
  'Ankle Eversion',
  'Strengthening exercise for the lateral ankle muscles using resistance band',
  'beginner', 'low', '10-25 reps',
  ARRAY['Yellow Perform Better Band']::text[],
  ARRAY['Peroneus Longus', 'Peroneus Brevis', 'Peroneus Tertius']::text[],
  ARRAY['Ankle Eversion']::text[],
  ARRAY['strength']::text[],
  'Sit with legs extended. Loop the yellow band around your foot and hold the other end. Turn your foot outward against the resistance, moving slowly and controlled. Return to neutral position.',
  'Ankle eversion with yellow band resistance',
  'Ankle eversion with stronger resistance band',
  'Ankle eversion without resistance',
  NULL
),
(
  'Toe Extension Plank',
  'Deep toe extension stretch that targets the plantar fascia and improves foot mobility',
  'beginner', 'moderate', '20-60 seconds',
  ARRAY['Chair']::text[],
  ARRAY['Toe Extensors', 'Plantar Fascia', 'Quadriceps', 'Core Stabilizers']::text[],
  ARRAY['Toe Extension', 'Ankle Dorsiflexion', 'Lumbar Neutral']::text[],
  ARRAY['mobility']::text[],
  'Stand or kneel in front of chair ready to use it for assistance. Put all 5 toes on each foot into a deep extension stretch put your elbows or hands on the chair and hold yourself up forcing a big stretch in your toes, bottom of foot/ankle, and perhaps even the quads. Keep your spine neutral.',
  'Toe extension plank with chair support',
  'Toe extension plank without chair support',
  'Toe extension stretch while seated',
  NULL
),
(
  'Wrist Flexion/Extension with Forearm Spinner',
  'Intense forearm strengthening exercise using weighted resistance',
  'beginner', 'high', '1-3 full reps up and down',
  ARRAY['Forearm Spinner', 'Two 2.5 lbs Plates']::text[],
  ARRAY['Flexor Carpi Radialis', 'Flexor Carpi Ulnaris', 'Extensor Carpi Radialis', 'Extensor Carpi Ulnaris']::text[],
  ARRAY['Wrist Flexion', 'Wrist Extension']::text[],
  ARRAY['strength']::text[],
  'Tie 2.5 lb plate to string attached to the spinner. Let the string be fully unwound and weight lying on the floor. Keeping elbows and spine straight, spin the spinner to raise the weight all the way to the top and control it back to the floor. Make sure to keep your posture and elbows straight, this one burns!',
  'Wrist flexion/extension with forearm spinner and 2.5 lb plate',
  'Wrist flexion/extension with heavier weight',
  'Wrist flexion/extension without weight',
  NULL
),
(
  'Reverse Fly',
  'Posterior deltoid and rhomboid strengthening exercise using resistance band',
  'intermediate', 'low', '6-15 reps',
  ARRAY['Purple Plastic Handle']::text[],
  ARRAY['Posterior Deltoids', 'Rhomboids', 'Middle Trapezius']::text[],
  ARRAY['Shoulder Horizontal Abduction', 'Shoulder External Rotation']::text[],
  ARRAY['strength']::text[],
  'Anchor the purple band to something sturdy with an equal amount of band left on each side. Stand facing the sturdy structure and grab the handles. Place your thumbs on the back side of the handles with the rest of your fingers. Start with light tension thinking you are trying to pull the sturdy object towards you with the band while pinching your shoulder blades together.',
  'Reverse fly with purple band',
  'Walk further away from sturdy structure',
  'Reverse fly without band',
  NULL
),
(
  'Standing Hip Abduction',
  'Single-leg balance exercise targeting hip abductor muscles',
  'intermediate', 'high', '8-20 reps',
  ARRAY['None']::text[],
  ARRAY['Gluteus Medius', 'Gluteus Minimus', 'Tensor Fasciae Latae']::text[],
  ARRAY['Hip Abduction']::text[],
  ARRAY['strength']::text[],
  'Holding onto something sturdy align your shoulder hip and ankle on one side allowing the other foot to hover off the ground. While keeping both legs as straight as possible bring the hovering leg as far away from the standing leg.',
  'Standing hip abduction with sturdy support',
  'Standing hip abduction with yellow perform better band',
  'Side-lying hip abduction',
  NULL
),
(
  'Side Plank',
  'Lateral core stabilization exercise targeting obliques and deep stabilizers',
  'beginner', 'moderate', '15-45 seconds each side',
  ARRAY['None']::text[],
  ARRAY['External Obliques', 'Internal Obliques', 'Quadratus Lumborum', 'Transverse Abdominis', 'Gluteus Medius']::text[],
  ARRAY['Cervical Neutral', 'Thoracic Lateral Flexion', 'Lumbar Lateral Flexion', 'Hip Neutral', 'Shoulder Stabilization']::text[],
  ARRAY['strength']::text[],
  'Lie on your side with legs extended and stacked. Support your upper body on your forearm, keeping elbow directly under shoulder. Lift hips off ground, creating a straight line from head to feet. Keep shoulders, hips, and ankles aligned. Hold position while breathing normally.',
  'Forearm side plank with straight body alignment',
  'Side plank with leg lifts or arm reaches',
  'Modified side plank with knees on ground or against wall',
  NULL
),
(
  'Overhead Shoulder Flexion on Foam Roller (PVC Pipe)',
  'A mobility drill to restore full shoulder flexion while reinforcing thoracic spine extension. This exercise teaches your shoulders to move overhead without compensation from the lower back.',
  'beginner', 'low', '8-12 controlled reps or 30-60 seconds continuous motion',
  ARRAY['Foam Roller', '5'' PVC Pipe']::text[],
  ARRAY['Anterior Deltoids', 'Middle Deltoids', 'Serratus Anterior', 'Lower Trapezius', 'Rectus Abdominis', 'Obliques']::text[],
  ARRAY['Shoulder Flexion', 'Thoracic Extension', 'Lumbar Neutral', 'Shoulder External Rotation']::text[],
  ARRAY['mobility']::text[],
  'Lie lengthwise on a foam roller so that your head and lumbar spine are supported. (Finding balance may be tricky at first — use your core to stabilize.) Grab the 5'' PVC Pipe with both hands, thumbs wrapped in the same direction as your fingers to promote slight external rotation at the shoulders. Keep ribs down and lower back flat on the roller. Slowly raise the 5'' PVC Pipe overhead as far as possible, focusing on motion coming from the shoulders and thoracic spine only. Avoid arching your low back — spine stays long and flat on the roller. Lower the bar back down under control.',
  'Overhead shoulder flexion with foam roller and 5'' PVC Pipe',
  'Overhead shoulder flexion with longer hold times or single-arm variations',
  'Overhead shoulder flexion without foam roller or with shorter range of motion',
  NULL
),
(
  'Supine Core Stability with Band Hold',
  'A core stability drill that integrates shoulder stability with trunk control. By holding the band under tension across the chest, you train the deep core to resist extension and reinforce spinal alignment.',
  'beginner', 'moderate', '2–3 sets of 20–40 seconds hold (progress to 60 seconds)',
  ARRAY['Purple Plastic Handle']::text[],
  ARRAY['Rectus Abdominis', 'Transverse Abdominis', 'Hip Flexors', 'Anterior Deltoids', 'Pectoralis Major', 'Serratus Anterior', 'Lower Trapezius', 'Gluteus Maximus', 'External Obliques', 'Internal Obliques']::text[],
  ARRAY['Shoulder Flexion', 'Lumbar Neutral', 'Hip Flexion']::text[],
  ARRAY['strength']::text[],
  'Anchor the purple plastic-handle band securely to a stable point just above head level when lying on your back. Lie on the floor with head near the anchor and feet pointed away. Grab the band with both hands, arms extended straight above the chest or slightly lower. Pull to create tension on the band, then hold the arms steady, keeping elbows locked. Keep ribs down and low back flat to the floor. For progression: Add alternating hip flexion/leg raises while maintaining the band hold.',
  'Supine band hold with arms extended, maintaining spinal contact',
  'Add alternating hip flexion/leg raises while maintaining band hold',
  'Reduce band tension or perform without band resistance',
  'https://www.youtube.com/embed/8pJqShYuhHU'
);
