// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfraninxxwqhjdkikfeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmcmFuaW54eHdxaGpka2lrZmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDAxNDEsImV4cCI6MjA2OTQxNjE0MX0.YWe2rBeyafqXwWXBaRplis_uWmo_oKSSI0hYJr02XAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});